### PR TITLE
Branch silvia

### PR DESCRIPTION
**Pull request by S1lv1aK**

### CODE REVIEW

**Comment by S1lv1aK** [comment]
I made an example with a working carousel based on something i found online.

I merged main into my branch so it should be simple to merge back into main.

**Comment by S1lv1aK** [comment]
Its currently separate from the dashboard. But it works.
Also, i think we should move the images into a separate folder in assets, i made a copy atm not to break the dashboard.

Should we find a way to embed html's into eachother?

**Comment by S1lv1aK** [comment]
I made it so the images are only in the img folder in assets.

A bit more organized. Updated dashboard as well.

**Comment by ziqian1125** [comment]
> Its currently separate from the dashboard. But it works.
> Also, i think we should move the images into a separate folder in assets, i made a copy atm not to break the dashboard.
> good idea to move the images unto a seperate folder,l adjust the assets
> Should we find a way to embed html's into eachother?

**Comment by ziqian1125** [comment]
yeah,it is more organized,the images puts in a seperate folder,thx for suggestions^^

**Pull request merged**
